config/routes.rb
Rails.application.routes.draw do
  resources :projects, only: %i[index show update] do
    resources :comments, only: %i[create edit update destroy]
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", :as => :rails_health_check

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates :content, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  has_many :comments

  def avatar_url
    "https://api.dicebear.com/9.x/icons/svg?seed=#{name}&backgroundColor=ffdfbf,ef9a9a,b6e3f4,9fa8da,80cbc4&icon=emojiLaughing,emojiSmile,emojiSmileUpsideDown,emojiWink"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  private

  def current_user
    # This would be done with a proper authentication system like Devise gem
    # This is just a simulation
    @current_user ||= User.first
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit update destroy]

  def edit
    raise "You can't edit this comment" unless @comment.user == current_user
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.project = Project.find(params[:project_id])
    @comment.user = current_user

    if @comment.save
      redirect_to project_comment_path(@comment.project, @comment), notice: "Comment was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    raise "You can't update this comment" unless @comment.user == current_user

    if @comment.update(comment_params)
      redirect_to project_path(@comment.project), notice: "Comment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @comment.destroy!

    redirect_to project_path(@comment.project), notice: "Comment was deleted."
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to project_path(@project), notice: "Project was successfully updated."
    else
      render project_path(@project), notice: "Something went wrong"
    end
  end

  private

  def project_params
    params.require(:project).permit(:closed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/comments/_comment.html.erb
<div class="mt-5 bg-violet-50 py-2.5 px-4 space-y-3 rounded-md">
  <div class="flex justify-between items-center">
    <div class="flex gap-3 items-center">
      <%= image_tag comment.user.avatar_url, class: "size-10 rounded-lg" %>
      <div class="flex flex-col gap-1 ">
        <%= comment.user.name %>
        <%= content_tag :span, l(comment.created_at, format: :short), class: "text-gray-600 text-xs" %>
      </div>
    </div>
    <% if current_user == comment.user %>
      <div class="flex gap-2">
        <%= link_to "Edit", edit_project_comment_path(project, comment), class: "text-xs text-violet-800 hover:text-violet-900 cursor-pointer" %>
        <%= button_to "Delete", project_comment_path(project, comment), method: :delete, data: { turbo_confirm: "Are you sure"}, class: "block text-xs text-violet-800 hover:text-violet-900 cursor-pointer" %>
      </div>
    <% end %>
  </div>
  <%= simple_format comment.content, class: "text-gray-600 text-sm font-normal " %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, url: url, class: "contents") do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-700 px-3 py-2 font-normal rounded-md mt-3">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul class="list-disc ml-6">
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :project_id %>

  <div class="my-5 flex gap-2 items-end">
    <%= form.text_area :content, rows: 4, class: ["shadow h-12 rounded-md border outline-hidden px-3 py-2 mt-2 w-full", {"border-gray-200 focus:outline-purple-600": comment.errors[:content].none?, "border-red-400 focus:outline-red-600": comment.errors[:content].any?}] %>

    <%= form.submit class: "rounded-lg px-3.5 py-2 bg-violet-500 hover:bg-violet-600 text-white inline-block font-normal cursor-pointer" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<div class="bg-white shadow-sm py-5 rounded-lg mx-auto w-1/2">
  <% content_for :title, "Editing comment" %>

  <div class="flex justify-between items-center px-8">
    <h1 class="font-medium tracking-wide text-2xl">Edit your comment</h1>
    <%= link_to "Back", project_path(@comment.project), class: "ml-2 rounded-md px-3.5 py-2 bg-gray-100 hover:bg-gray-50 inline-block font-normal text-gray-900" %>
  </div>
  <div class="border-b-2 border-gray-100 mt-2"></div>
  <div class="mt-10 px-8">
    <%= render "form", comment: @comment, url: project_comment_path(@comment.project, @comment) %>
  </div>
  </div>
</div>

app/views/comments/new.html.erb
<div class="bg-white shadow-sm py-5 rounded-lg mx-auto w-1/2">
  <% content_for :title, "New comment" %>

  <div class="flex justify-between items-center px-8">
    <h1 class="font-medium tracking-wide text-2xl">New comment</h1>
    <%= link_to "Back", project_path(@comment.project), class: "ml-2 rounded-md px-3.5 py-2 bg-gray-100 hover:bg-gray-50 inline-block font-normal text-gray-900" %>
  </div>
  <div class="border-b-2 border-gray-100 mt-2"></div>
  <div class="mt-10 px-8 flex-1">
    <%= render "form", comment: @comment, url: project_comments_path(@comment.project) %>
  </div>
</div>

app/views/layouts/_alerts.html.erb
<% if notice.present? %>
  <p class="p-3 w-full bg-green-50 mb-5 text-green-700 font-normal rounded-md inline-block" id="notice"><%= notice %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConversationHistory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <main class="container mx-auto mt-10 px-5 w-3/4">
      <%= render "layouts/alerts" %>

      <%= yield %>
    </main>
  </body>
</html>

app/views/projects/index.html.erb
<div class="grid grid-cols-3 gap-4">
  <% @projects.each do |project| %>
    <div class="bg-white text-center shadow rounded-lg">
      <div class="flex flex-col justify-center items-center py-8">
        <%= image_tag "chat_2", class: "size-20 mb-15" %>
        <%= link_to project_path(project), class: "font-normal text-gray-900 bg-violet-100 rounded-md px-3.5 py-2" do %>
          <%= content_tag :span, project.name %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<div class="bg-white shadow-sm py-6 rounded-lg">
  <div class="flex justify-between mb-3 px-8">
    <h1 class="text-2xl tracking-wide font-medium"><%= @project.name %></h1>
    <%= link_to "Back", projects_path, class: "ml-2 rounded-md px-3.5 py-2 bg-gray-100 hover:bg-gray-50 inline-block font-normal" %>
  </div>

  <div class="border-b-2 border-gray-100"></div>

  <div class="flex justify-end items-center gap-3 px-8 mt-5">
    <div data-controller="submitter">
      <%= form_with model: @project, url: project_path(@project), method: :patch do |f| %>
        <div class="flex gap-2 items-center">
          <p class="text-sm text-gray-00">Close</p>
          <%= f.check_box :closed, data: { action: "click->submitter#submit" } %>
        </div>
        <%= f.button "Update", data: { submitter_target: "button" }, class: "hidden" %>
      <% end %>
    </div>

    <% if @project.closed %>
      <div class="bg-red-100 text-sm text-red-800 px-4 py-1 rounded-full">Closed</div>
    <% else %>
      <div class="bg-green-100 text-sm text-green-700 px-4 py-1 rounded-full">Open</div>
    <% end %>
  </div>

  <div class="px-8">
    <% @project.comments.each do |comment| %>
      <%= render "comments/comment", comment: comment, project: @project %>
    <% end %>
  </div>

  <div class="mt-10 px-8">
    <%= render "comments/form", comment: Comment.new, url: project_comments_path(@project) %>
  </div>
</div>